name: python-tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: apt-get
        run: |
          sudo apt-get update && sudo apt-get install libldap2-dev libsasl2-dev
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pyOpenSSL && pip install -r requirements.txt
      - name: Test Level-1
        run: |
          python Level-1/tests.py
          python Level-1/hack.py
      - name: Test Level-3
        run: |
          python Level-3/tests.py
          python Level-3/hack.py
      - name: Test Level-4
        run: |
          python Level-4/tests.py
          python Level-4/hack.py
